jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

amazon:
  aws:
    region: ${AWS_REGION}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}